# name: Automated deployment

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   trigger-deploy:
#     runs-on: ubuntu-latest
#     # env:
#     #   DEPLOYS: ${{ steps.read-json.outputs.DEPLOYS }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Read deploy.json
#         id: read-json
#         run: |
#           #deploys=$(cat deploy.json)
#           echo "DEPLOYS=$(cat deploy.json | jq .)" >> $GITHUB_OUTPUT
          
#         shell: bash

#       - name: validacao output json
#         run: |
#            echo ${{ steps.read-json.outputs.DEPLOYS }}
#         shell: bash


#           # DEPLOYS: ${{ steps.read-json.outputs.deploys }}
#           # environment: ${{ inputs.environment }}
#           # image-version: ${{ inputs.image-version }}


name: Trigger Other Workflow

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Trigger multiple workflows
      run: |
           for ROW in $(echo "${cat deploy.json}" | jq -r '.[] | @base64'); do
                 _jq() {
                   echo ${ROW} | base64 --decode | jq -r ${1}
                 }

                 REPOSITORY=$(_jq '.repository')
                 WORKFLOW_FILE=$(_jq '.workflow_file')
                 TAG=$(_jq '.tag')

                 curl -X POST -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: token ${{ secrets.PAT }}" \
                 https://api.github.com/repos/malaquiasLAB/$REPOSITORY/actions/workflows/$WORKFLOW_FILE/dispatches \
                 -d '{"ref":"$TAG"}'
            done