# name: Automated deployment

# on:
#   push:
#     branches:
#       - develop

# jobs:
#   trigger-deploy:
#     runs-on: ubuntu-latest
#     # env:
#     #   DEPLOYS: ${{ steps.read-json.outputs.DEPLOYS }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Read deploy.json
#         id: read-json
#         run: |
#           #deploys=$(cat deploy.json)
#           echo "DEPLOYS=$(cat deploy.json | jq .)" >> $GITHUB_OUTPUT
          
#         shell: bash

#       - name: validacao output json
#         run: |
#            echo ${{ steps.read-json.outputs.DEPLOYS }}
#         shell: bash


#           # DEPLOYS: ${{ steps.read-json.outputs.deploys }}
#           # environment: ${{ inputs.environment }}
#           # image-version: ${{ inputs.image-version }}


name: Trigger Other Workflow

on: [push]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger workflow repo1
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: Bearer ${{ secrets.PAT }}" \
        https://api.github.com/repos/malaquiasLAB/repo1/dispatches \
        -d '{"event_type":"custom_event"}'



    - name: Trigger workflow repo2
      run: |
        curl -X POST -H "Accept: application/vnd.github.v3+json" \
        -H "Authorization: token ${{ secrets.PAT }}" \
        https://api.github.com/repos/malaquiasLAB/repo2/dispatches \
        -d '{"event_type":"custom_event"}'