name: Automated Deployment

on:
  push:
    branches:
      - develop
      - main

jobs:
  trigger_multiple_workflows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Trigger multiple workflows
      run: |
           for ROW in $(cat deploy.json | jq -r '.[] | @base64'); do
                 _jq() {
                   echo ${ROW} | base64 --decode | jq -r ${1}
                 }

                 REPOSITORY=$(_jq '.repository')
                 WORKFLOW_FILE=$(_jq '.workflow_file')
                 TAG=$(_jq '.tag')

                 curl -s -X POST -H "Accept: application/vnd.github.v3+json" \
                 -H "Authorization: token ${{ secrets.PAT }}" \
                 https://api.github.com/repos/malaquiasLAB/$REPOSITORY/actions/workflows/$WORKFLOW_FILE/dispatches \
                 -d '{"ref":"'$TAG'"}'

                 if [ $? -eq 0 ]; then
                   echo "Workflow $WORKFLOW_FILE triggered successfully for $REPOSITORY"
                 else
                   echo "Failed to trigger workflow $WORKFLOW_FILE for $REPOSITORY"
                 fi
            done
      shell: bash