name: Automated deployment

on:
  push:
    branches:
      - develop

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    # env:
    #   DEPLOYS: ${{ steps.read-json.outputs.DEPLOYS }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read deploy.json
        id: read-json
        run: |
          echo "DEPLOYS=$(cat deploy.json)" >> $GITHUB_OUTPUT
          
        shell: bash

      - name: validacao output json
        run: |
           echo $DEPLOYS #echo ${{ steps.read-json.outputs.DEPLOYS }}
        shell: bash


          # DEPLOYS: ${{ steps.read-json.outputs.deploys }}
          # environment: ${{ inputs.environment }}
          # image-version: ${{ inputs.image-version }}