name: Trigger Reusable Workflow

on:
    workflow_dispatch:

jobs:
    call-reusable:
        uses: malaquiasLAB/reusable-workflows/.github/workflows/reusable_001.yaml@main
        with:
            example-input: |
                file01
                file02
                file03